# Generated by Django 3.2 on 2021-08-12 10:27

import LOGIN.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LOGIN', '0018_remove_workshop_noofevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('ranking', models.FloatField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to=LOGIN.models.Users.upload_photo)),
                ('resume', models.ImageField(blank=True, null=True, upload_to=LOGIN.models.Users.upload_file)),
            ],
        ),
        migrations.AlterField(
            model_name='feed',
            name='Video',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
