# Generated by Django 3.2 on 2021-08-26 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LOGIN', '0020_auto_20210822_0035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150)),
                ('About', models.CharField(max_length=1000)),
                ('Media', models.FileField(default='', upload_to='uploads/')),
            ],
            options={
                'db_table': 'Member',
            },
        ),
    ]
