# Generated by Django 3.2 on 2021-08-21 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LOGIN', '0019_auto_20210812_1827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='employee_id',
            new_name='username',
        ),
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
