# Generated by Django 3.2 on 2021-08-26 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LOGIN', '0021_member'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='About',
            new_name='Lives',
        ),
        migrations.RemoveField(
            model_name='member',
            name='Media',
        ),
        migrations.AddField(
            model_name='member',
            name='Study',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
